version: '2'
services:
    phpmyadmin: # web интерфейс сервера базы данных
        image: phpmyadmin/phpmyadmin
        ports:
          - 8183:80
        environment:
          - PMA_HOSTS=db-mysql,db-mysql-test # для выбора сервера бд из выпадающего списка
    db-mysql: # сервер mysql с рабочей базой данных
        image: mysql:5.7
        ports:
          - 3316:3306
        volumes:
          - mysql_data:/var/lib/mysql
          - ./docker/mysql/conf.d:/etc/mysql/conf.d
        environment:
          MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
          MYSQL_DATABASE: ${MYSQL_DB_NAME}
    db-mysql-test: # сервер mysql с тестовой базой данных
        image: mysql:5.7
        ports:
          - 3326:3306
        volumes:
          - mysql_data_test:/var/lib/mysql
        environment:
          MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
          MYSQL_DATABASE: ${MYSQL_DB_NAME_TEST}
    nginx:
        image: nginx
        ports:
            - 80:80
        volumes:
            - ./:/app
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
    php:
        build: docker/php
        user: 1000:1000
        working_dir: /app
        volumes:
            - ./:/app
            - ~/.composer/cache:/var/www/.composer/cache
        environment:
          # внутри network default
          - XDEBUG_CONFIG=remote_host=php
    memcached_server:
        image: memcached:alpine

    phpmemcachedadmin:
       image: jacksoncage/phpmemcachedadmin
       ports:
         - 8093:80

volumes: # именованные тома
  mysql_data: # рабочая база
  mysql_data_test: # тестовая база
