version: '2'
services:
    composer:
        image: composer
        user: 1000:1000
        working_dir: /app
        volumes:
            - ./:/app
    nginx:
        image: nginx
        ports:
            - 8080:80
        volumes:
            - ./:/app
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - web
    web:
        build: docker/php
        user: 1000:1000
        working_dir: /app
        volumes:
            - ./:/app
